### ISSUE TITLE
ssc not connecting to localhost

### ISSUE THREAD

**Issue by Jaxelr** [justinlettau/sql-source-control#37]
## Type
What kind of issue is this?

```
[ X ] Bug report.
[ ] Feature request.
```

## Current Behavior

Using the following connection definition:

``` json
{
  "connections": [
    {
      "name": "dev",
      "server": "localhost",
      "database": "PDV02",  
      "port": 1433,
      "user": "sa",
      "password": "password"
    }
  ]
}
```

i get the following error message (could not connect):

``` json
{ ConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
    at Connection.tedious.once.err (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Connection.socketError (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connection.js:1016:14)
    at C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connection.js:861:25
    at SequentialConnectionStrategy.connect (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connector.js:154:9)
    at Socket.onError (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connector.js:170:16)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
  code: 'ESOCKET',
  originalError:
   { ConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
       at ConnectionError (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\errors.js:12:12)
       at Connection.socketError (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connection.js:1016:30)
       at C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connection.js:861:25
       at SequentialConnectionStrategy.connect (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connector.js:154:9)
       at Socket.onError (C:\Users\Jaxel\AppData\Roaming\npm\node_modules\sql-source-control\node_modules\tedious\lib\connector.js:170:16)
       at Socket.emit (events.js:182:13)
       at emitErrorNT (internal/streams/destroy.js:82:8)
       at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     message:
      'Failed to connect to localhost:1433 - Could not connect (sequence)',
     code: 'ESOCKET' },
  name: 'ConnectionError' }
```

## Expected behavior

To connect properly to localhost when submitting connection requests

## Steps to Reproduce

ssc init (using the information above on the main configuration file)
ssc pull 

## Other Information

I confirmed the password is correct.
I tried by ip 127.0.0.1, using . , localhost and the machine name as a server property.
I confirmed the port is the default port of the instance i am testing.
The SQL Server Version is 12.0.4237.0 (2014).
Confirmed this command works for servers on my network, it simply doesn't work for local machine.
Tested on both Virtual and physical environment, and the behavior is similar.
Tested on multiple databases.

**Comment by justinlettau** [comment]
Can you try enabling the TCP/IP protocol (disabled by default)?

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol?view=sql-server-2017#to-enable-a-server-network-protocol

**Comment by Jaxelr** [comment]
Thx for the quick reply, From what i checked it was enabled.

![image](https://user-images.githubusercontent.com/5913008/44160043-29f8cb00-a087-11e8-8013-cbda42c230dc.png)

**Comment by justinlettau** [comment]
It looks like you are looking at the TCP/IP for the client configuration. Can you check the TCP/IP protocol under "SQL Server Network Configuration"?

![image](https://user-images.githubusercontent.com/5008151/44160427-64169c80-a088-11e8-88ca-106c060a98d1.png)

**Comment by Jaxelr** [comment]
Ahhh yes! my apologies, you are correct, that was the problem. Thank you for your time.

**Comment by justinlettau** [comment]
No problem! I'll add something to the readme for future reference.
